### ISSUE TITLE
Error: Unknown exception NoMethodError

### ISSUE THREAD

**Issue by rivets** [manton/jsonfeed-validator#1]
I just tried your feed validator and am getting the error in the subject line. I have no idea if it is my feed that is bad (why I was looking for a feed validator!) or if I've tickled an issue. The feed link I used is

http://catless.ncl.ac.uk/risks.json

**Comment by sonicdoe** [comment]
While the validator shouldn’t throw an exception, I can tell you where the error lies within your feed: You specify a top-level `image` property, however, the `image` property is only applicable to individual feed items.
