### ISSUE TITLE
Validator should catch invalid JSON

### ISSUE THREAD

**Issue by sardisson** [manton/jsonfeed-validator#3]
In [a recent conversation](https://micro.blog/artkavanagh/6687469) about a feed that the Validator said was valid but Micro.blog was unable to handle, we discovered that the Validator apparently does not check the JSON, just the overall “feed structure”?

Since presumably one cannot have a valid JSON Feed without also having valid JSON (the former being a superset of the latter?), it would be useful for the Validator to also report on the validity of the JSON itself and report whatever error cancels the parsing—or, barring that, link to an online JSON validator that people can use to check the JSON of their JSON Feed, along with a reminder to do just that.

**Comment by manton** [comment]
I think this is handled correctly now with an appropriate error.
