### ISSUE TITLE
vulnerability in JSONFeed Validator

### ISSUE THREAD

**Issue by DanielRuf** [manton/jsonfeed-validator#4]
Hi @manton,

I've tried to reach out to you via email but I've received no response regarding a vulnerability that I found.

I've also sent you a contact request on LinkedIn right now so we can discuss the technical details in private.

**Comment by manton** [comment]
Thanks @DanielRuf! Sorry I missed replying to your email. I see it now and will follow up.

**Comment by DanielRuf** [comment]
Still relevant.
